[debug] Waiting for thread run-main-0 to terminate.
[error] (run-main-0) java.lang.ClassNotFoundException: scala.Int
[error] java.lang.ClassNotFoundException: scala.Int
[error] 	at sbt.internal.inc.classpath.ClasspathFilter.loadClass(ClassLoaders.scala:74)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at java.lang.Class.forName0(Native Method)
[error] 	at java.lang.Class.forName(Class.java:348)
[error] 	at akka.actor.ReflectiveDynamicAccess.$anonfun$getClassFor$1(ReflectiveDynamicAccess.scala:21)
[error] 	at scala.util.Try$.apply(Try.scala:209)
[error] 	at akka.actor.ReflectiveDynamicAccess.getClassFor(ReflectiveDynamicAccess.scala:20)
[error] 	at akka.serialization.Serialization.$anonfun$bindings$3(Serialization.scala:313)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:739)
[error] 	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:231)
[error] 	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
[error] 	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:738)
[error] 	at akka.serialization.Serialization.<init>(Serialization.scala:311)
[error] 	at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:15)
[error] 	at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:12)
[error] 	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:880)
[error] 	at akka.actor.ExtensionId.apply(Extension.scala:78)
[error] 	at akka.actor.ExtensionId.apply$(Extension.scala:77)
[error] 	at akka.serialization.SerializationExtension$.apply(SerializationExtension.scala:12)
[error] 	at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:203)
[error] 	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:796)
[error] 	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:793)
[error] 	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:793)
[error] 	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:809)
[error] 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:244)
[error] 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:287)
[error] 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:262)
[error] 	at Main$.delayedEndpoint$Main$1(Main.scala:7)
[error] 	at Main$delayedInit$body.apply(Main.scala:5)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.App.main(App.scala:76)
[error] 	at scala.App.main$(App.scala:74)
[error] 	at Main$.main(Main.scala:5)
[error] 	at Main.main(Main.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:89)
[error] 	at sbt.Run.run0(Run.scala:83)
[error] 	at sbt.Run.execute$1(Run.scala:61)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:73)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error] 	at sbt.Run$.executeTrapExit(Run.scala:120)
[error] 	at sbt.Run.run(Run.scala:73)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$5(Defaults.scala:1152)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$5$adapted(Defaults.scala:1147)
[error] 	at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:359)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at scala.util.Try$.apply(Try.scala:209)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:282)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (frontend/compile:run) Nonzero exit code: 1
[error] Total time: 13 s, completed Nov 8, 2017 8:33:01 PM

